### ISSUE TITLE
Should update to a V4 version sothat it still work

### ISSUE THREAD

**Issue by gabrielstuff** [feathers-plus/validate-joi#14]
The hook needs some changes to work with the hooks from the V4 version of feathersjs.

Next has been deprecated and thus makes unusable this wonderful validation hook.

**Comment by asamolion** [comment]
@gabrielstuff I've forked this and created a v4 compatible version.

https://github.com/asamolion/feathers-hooks-validate-joi

Let me know if that works for you. 

Thanks in advance. :+1:

**Comment by marshallswain** [comment]
Fixed in `@feathers-plus/validate-joi@3.0.0`.
