### ISSUE TITLE
v4 compatibility

### ISSUE THREAD

**Issue by asamolion** [feathers-plus/validate-joi#15]
@eddyystop What is your status on this package? Are you going to maintain it?

If not, I'm interested in working on this. I've already forked and made a FeathersJS v4 compatible version of this.

https://github.com/asamolion/feathers-hooks-validate-joi

Kind regards,
Osama

**Comment by marshallswain** [comment]
Fixed in `@feathers-plus/validate-joi@3.0.0`.
