### ISSUE TITLE
Option to validate get methods

### ISSUE THREAD

**Issue by jay-jlm** [feathers-plus/validate-joi#2]
I'm wondering why it's not currently possible to use this module to validate parameters of Service.get() methods

**Comment by eddyystop** [comment]
The intent of the hook was to validate data before it was written to the DB, hence validate `hook.data`.

What is the use case for a `.get`? What is the use case for validating `hook.params` which is always populated with Feathers props such as `provider` and `app`?

**Comment by hodorswit** [comment]
I have a similar use case, with several GET/FIND service methods having a combination of required/optional parameters. 

Joi is arguably overkill, but I'm already using it for form validation and it would be nice to use a single, consistent abstraction to validate `hook.params.query` or `hook.data`.

**Comment by eddyystop** [comment]
The code uses `.getItems(hook);` and `.replaceItems`. That should work as a before hook (for hook.data) as well as an after hook. Am I wrong?
