### ISSUE TITLE
Hi are any typescript definitions for this package

### ISSUE THREAD

**Issue by joseDaKing** [feathers-plus/validate-joi#21]
Hi i am wondering if there are any typescript definitions for this project, i really want to use it typescript.

**Comment by digitalcortex** [comment]
Check our my fork https://github.com/digitalcortex/validate-joi.
I did a pull request, maybe the devs would be able to accept it.

**Comment by joseDaKing** [comment]
Great, i think will use type definitions manually in may code

**Comment by marshallswain** [comment]
Thanks @digitalcortex for the PR.  I've merged it and released it as `@feathers-plus/validate-joi@3.3.0`.
