### ISSUE TITLE
Validating patch method data

### ISSUE THREAD

**Issue by adamvr** [feathers-plus/validate-joi#5]
Hi guys, I'm interested to know if you've found a good way of validating patch method data with joi. The problem is, of course, that you can't validate the whole schema on a patch request since you don't have the entire object to work with, just the patch data. The way I see it, there's a couple of ways of doing it:

1. Running joi in something like 'patch mode,' where you would skip `required()` validations and run `joi.validate()` with `noDefaults: true`. This would allow you to validate patch data in isolation but as far as I can tell there's no way of skipping required validations in vanilla joi (you can hack your way around it a bit with `requiredKeys()` but then you would need to sneak in required fields through `meta()` or have a separate list of required keys rather than using `required()`).

2. Looking up the previous version of the object and running the patch and object through something like https://github.com/MarkHerhold/json-patch-joi. The problem with this approach is that you will need to load the whole previous version each time you want to run a patch request.

Any ideas there?

**Comment by eddyystop** [comment]
I haven't heard of any options other than those 2. It an annoying issue with every validator, not just Joi.

Let's keep this issue open for people to share their thoughts.

**Comment by danlupascu** [comment]
Has anyone come with a decent solution for this issue?

**Comment by brothergiez** [comment]
> Has anyone come with a decent solution for this issue?

https://medium.com/@cristophadamsugianto/membuat-dynamic-validate-untuk-patch-method-menggunakan-joi-d43c4fbdd11

**Comment by litti** [comment]
Because google led me here: tailor (https://hapi.dev/module/joi/api/?v=17.1.1#anytailortargets) and context option (https://github.com/hapijs/joi/issues/1683#issuecomment-446647506) can be used for some usecases too.

**Comment by marshallswain** [comment]
The `validateProvidedData` hook does a great job of validating patch requests.  It won't handle every use case, but it gets us most of the way there.

https://github.com/feathers-plus/validate-joi#validateprovideddata-hook
